### ISSUE TITLE
The 0 issue 

### ISSUE THREAD

**Issue by shad-ct** [mohammedfarhannp/Calc_GUI#1]
![image](https://github.com/user-attachments/assets/55904def-7438-4fc8-94fd-e33aa3b7a2b4)

Thats a nice project! good job! 
The calculator starts with the number 0 itself, maybe leaving it blank would help. It is minimal; indeed, I suppose it's hard to do multiple operation at a time because of the signs being in the middle of the calculator unlike the traditional calculator  

Anyway, you did a great job. I won't be alone to make something like that currently due to my lack of knowledge. 

You did great!

**Comment by mohammedfarhannp** [comment]
I have created this for assignment work; the task was to create and use a module with all the basic function, therefore I needed to get 2 different input fields with integer value and then use the operator field with dictionary to call the function from the module but what you are asking for is very easy and possible, but it would be hard to implement the custom module part.

**Comment by shad-ct** [comment]
if that's the case, you did ahead of the league 👍
